global_costmap:
  update_frequency: 5
  publish_frequency: 5
  global_frame: map
  robot_base_frame: base_footprint
  transform_tolerance: 0.5
  rolling_window: false
  track_unknown_space: true
  robot_radius: 0.5
  footprint_padding: 0.01
  footprint: [[0.55, 0.45], [0.55, -0.45], [-0.55, -0.45], [-0.55, 0.45]]
  plugins:
      - {name: static_map,             type: "costmap_2d::StaticLayer"}
      - {name: inflation_layer,        type: "costmap_2d::InflationLayer"}
      - {name: obstacle_layer,         type: "costmap_2d::ObstacleLayer"}
  static:
    map_topic: /map
    subscribe_to_updates: true

  obstacle_layer:
    observation_sources: laser
    laser: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: True, clearing: True, obstacle_range: 3.0, raytrace_range: 6.0, inf_is_valid: True}
  
  inflation_layer:
    inflation_radius: 1.0
    cost_scaling_factor: 1.0
