local_costmap:
  update_frequency: 5
  publish_frequency: 5
  global_frame: map
  robot_base_frame: base_footprint
  transform_tolerance: 0.5
  rolling_window: true
  resolution: 0.1
  footprint: [[0.45, 0.25], [0.45, -0.25], [-0.45, -0.25], [-0.45, 0.25]]
  footprint_padding: 0.0
  robot_radius: 0.5
  width: 5
  height: 5
  plugins:
       - {name: static_map,             type: "costmap_2d::StaticLayer"}
       - {name: inflation_layer,        type: "costmap_2d::InflationLayer"}
       - {name: obstacle_layer,         type: "costmap_2d::ObstacleLayer"}
  static:
    map_topic: /move_base/local_costmap/costmap
    subscribe_to_updates: true
  
  obstacle_layer:
    observation_sources: laser
    laser: {data_type: LaserScan, sensor_frame: laser, topic: /scan, marking: true, clearing: true, min_obstacle_height: -0.05, obstacle_range: 3.0, raytrace_range: 6.0, inf_is_valid: true}
  
  inflation_layer:
    inflation_radius: 1
    cost_scaling_factor: 50.0 # larger number = lower cost elevation
