target_frame: d435_link
transform_tolerance: 0.01
min_height: 0.0
max_height: 1.0
angle_min: -1.570
angle_max: 1.5708
angle_increment: 0.0087
scan_time: 0.3333
range_min: 0.45
range_max: 4.0
use_inf: True
inf_epsilon: 1.0
