DWAPlannerROS:
  acc_lim_th: 5.0
  acc_lim_x: 5.0
  acc_lim_trans: 5.0

  max_vel_x: 0.5
  min_vel_x: -0.5

  max_vel_trans: 0.5
  min_vel_trans: -0.5

  max_vel_theta: 0.5
  min_vel_theta: -0.5

  sim_time: 1.0
  #sim_granularity: 0.025
  vx_samples: 40
  #vy samples: 0
  vtheta_samples: 50

  #goal_distance_bias: 10.0
  #path_distance_bias: 32.0
  occdist_scale: 10

  #stop_time_buffer: 0.2
  #oscillation_reset_dist: 0.05

  #forward_point_distance: 0.3

  scaling_speed: 0.3
  max_scaling_factor: 0

  #sim_period: 0.1

  xy_goal_tolerance: 0.2 #meter
  yaw_goal_tolerance: 0.3 #radians
  #latch_xy_goal_tolerance: false
