DWAPlannerROS:
  acc_lim_theta: 3.4
  acc_lim_x: 10.0
  acc_lim_trans: 10.0

  max_vel_x: 0.8
  min_vel_x: 0.6

  max_vel_trans: 0.8
  min_vel_trans: 0.6

  max_vel_theta: 1.6
  min_vel_theta: 1.4

  max_rot_vel: 1.6
  min_rot_vel: 1.4

  sim_time: 2.0
  #sim_granularity: 0.025
  #vx_samples: 30
  #vy samples: 0
  #vtheta_samples: 40

  #goal_distance_bias: 10.0
  #path_distance_bias: 32.0
  occdist_scale: 10

  #stop_time_buffer: 0.2
  #oscillation_reset_dist: 0.05

  #forward_point_distance: 0.3

  #scaling_speed: 0.25
  #max_scaling_factor: 0.5

  #sim_period: 0.1

  xy_goal_tolerance: 0.2 #meter
  yaw_goal_tolerance: 0.2 #radians
  latch_xy_goal_tolerance: false
