global_costmap:
  update_frequency: 2
  publish_frequency: 1
  global_frame: map
  robot_base_frame: base_footprint
  transform_tolerance: 0.5
  static_map: false
  rolling_window: false
  track_unknown_space: true
  footprint: [[0.50, 0.30], [0.50, -0.30], [-0.50, -0.30], [-0.50, 0.30]]
  footprint_padding: 0.0

  plugins:
      - {name: static_map,             type: "costmap_2d::StaticLayer"}
      - {name: inflation_layer,        type: "costmap_2d::InflationLayer"}
      - {name: obstacle_layer,         type: "costmap_2d::ObstacleLayer"}
  static:        
    map_topic: /map
    subscribe_to_updates: true

  sensor:
    observation_sources: laser
    laser: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: True, clearing: True, obstacle_range: 5.5, raytrace_range: 6.0, inf_is_valid: True}

  inflation:
    inflation_radius: 0.3
    cost_scaling_factor: 10.0 
