global_costmap:
  update_frequency: 5
  publish_frequency: 5
  global_frame: map
  robot_base_frame: base_footprint
  transform_tolerance: 0.5
  static_map: false
  rolling_window: false
  track_unknown_space: true
  robot_radius: 0.5
  footprint_padding: 0.01
  footprint: [[0.80, 0.60], [0.80, -0.60], [-0.80, -0.60], [-0.80, 0.60]]
  plugins:
      - {name: static_map,             type: "costmap_2d::StaticLayer"}
      - {name: inflation_layer,        type: "costmap_2d::InflationLayer"}
      - {name: obstacle_layer,         type: "costmap_2d::ObstacleLayer"}
  static:        
    map_topic: /map
    subscribe_to_updates: true

  sensor:
    observation_sources: laser
    laser: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: True, clearing: True, obstacle_range: 1.0, raytrace_range: 6.0, inf_is_valid: True}
  inflation:
    inflation_radius: 0.3
    cost_scaling_factor: 20.0 
