local_costmap:
  update_frequency: 2
  publish_frequency: 1
  global_frame: map
  robot_base_frame: base_footprint
  transform_tolerance: 0.5
  static_map: false
  rolling_window: true
  footprint: [[0.36, 0.20], [0.36, -0.20], [-0.36, -0.20], [-0.36, 0.20]]
  footprint_padding: 0.0
  width: 2
  height: 2
  plugins:
       - {name: static_map,             type: "costmap_2d::StaticLayer"}
       - {name: inflation_layer,        type: "costmap_2d::InflationLayer"}
       - {name: obstacle_layer,         type: "costmap_2d::ObstacleLayer"}
  static:        
    map_topic: /move_base/local_costmap/costmap
    subscribe_to_updates: true

  obstacle_layer:
    observation_sources: laser
    laser: {data_type: LaserScan, sensor_frame: laser, topic: /scan, marking: true, clearing: true, min_obstacle_height: -0.05, obstacle_range: 5.5, raytrace_range: 6.0, inf_is_valid: true}
        

  inflation:
    inflation_radius: 0.36
    cost_scaling_factor: 3.0 # larger number = lower cost elevation

