#shutdown_costmaps: false
#planner_frequency: 5.0 #1.0
controller_frequency: 5.0 #1.0
#planner_patience: 1.0
#controller_patience: 1.0
conservative_reset_dist: 0.2
#oscillation_timeout: 1.0
#oscillation_distance: 0.2
#max_planning_retries: -1
recovery_behavior_enabled: true